CREATE DATABASE IF NOT EXISTS user_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS catalog_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS trade_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS agent_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
CREATE DATABASE IF NOT EXISTS knowledge_db CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

GRANT ALL PRIVILEGES ON user_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON catalog_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON trade_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON agent_db.* TO 'app'@'%';
GRANT ALL PRIVILEGES ON knowledge_db.* TO 'app'@'%';
